FROM rust:1.73-slim

# Install required tools
RUN apt-get update && apt-get install -y libpq-dev pkg-config openssl

WORKDIR /app

# Speed up builds using Docker layer caching
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs && cargo build --release && rm -r src

# Copy source
COPY . .

# Build the actual binary
RUN cargo build --release

# Expose the port
EXPOSE 3000

# Run the app
CMD ["./target/release/drive_clone"]
